import { config } from "dotenv";
config();
export const atlas = process.env.DBURL;
export const appdb = process.env.DB;
export const isocountriesdata = process.env.ISOCOUNTRIES;
export const gocalertsdata = process.env.GOCALERTS;
export const alertcollection = process.env.ALERTCOLLECTION;
export const advisorycollection = process.env.ADVISORYCOLLECTION;
export const port = process.env.PORT;
export const graphql = process.env.GRAPHQLURL;
export const server = process.env.SERVER;
